### ISSUE TITLE
StackOverFlow error 

### ISSUE THREAD

**Issue by Dgotlieb** [romankh3/image-comparison#17]
Hi,
Whenever I use an image that is not small, I'm getting a StackOverFlow error on the recursion.
Any ideas? thoughts? 

Thanks.

**Comment by romankh3** [comment]
Hi,
Could you provide images? I don't not for sure what's going on, nevertheless, I could debug it.

**Comment by Dgotlieb** [comment]
Hi,

Thanks for the quick answer..
[https://ibb.co/jwP7wc
https://ibb.co/mEW99x](url)

**Comment by romankh3** [comment]
they don't exist.
<img width="861" alt="2018-04-07 10 07 40" src="https://user-images.githubusercontent.com/16310793/38452359-8f4c222e-3a4b-11e8-9d87-1841fe92d2ff.png">

**Comment by Dgotlieb** [comment]
Hi,
Sorry for the overhead.. 
The links work, but you will need to use link text rather than link address. 
For some reason, github breaks the reference of the link. 
Thanks

**Comment by romankh3** [comment]
understood!
I tried to use this images and got the same... I will think about it, thanks for this case.
If you get how to do it - create Pull Request with updates from `master` branch.

**Comment by Dgotlieb** [comment]
Hi,
I was able to reproduce in two scenarios:
1. Image format was **.jpg** and not **.png**
2. Threshold value was high.

Still no clue on how to fix it..

**Comment by romankh3** [comment]
I think I found an issue. 
`b1` and `b2` have different bit color. b1 has 8-bit color, b2 has 32-bit color.
That's why we've got all values of the `matrix` are `1`.

**Comment by romankh3** [comment]
Fixed.
Thanks for this case.

**Comment by akondas** [comment]
This problem still exists for larger images, open a new issue or paste sample data here?

**Comment by romankh3** [comment]
@akondas, Please, create a new issue with all the details and test images.
